# Config file for automatic testing at travis-ci.org
language: python

sudo: false

cache:
   directories:
      - $HOME/.cache/pre-commit

dist: xenial

matrix:
    fast_finish: true
    include:
      - env: TOXENV=py35
        python: 3.5
      - env: TOXENV=py36
        python: 3.6
      - env: TOXENV=py37
        python: 3.7
      - env: TOXENV=py38
        python: 3.8
      - env: TOXENV=black
        python: 3.7
      - env: TOXENV=docs
        python: 3.7
      - env: TOXENV=hooks
        python: 3.7
    allow_failures:
      - env: TOXENV=py38

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - sudo -H pip install --upgrade pip
    - pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox -e $TOXENV

before_deploy:
    - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: '{{ cookiecutter.github_username }}'
  password:
    secure: 'Encrypted password'
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+[\.]?[a-c-]?[0-9]?[\w-]+\b
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}
    python: 3.7
